#theme: minima
#theme:dinky

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme 

title: Yet another boring site
author: Ivan Pashchenko
description: a 18578th Github pages test
